/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yelp.data.elasticsearch.loader;

import yelp.data.elasticsearch.loader.index.utils.ElasticsearchIndexCreator;

import java.io.File;

public class App {

    public static void main(String[] args) {

        File datasetDirectory = new File(".");
        YelpDataLoader loader = new YelpDataLoader(datasetDirectory);

    }
}
